# Generated by Django 4.0.3 on 2022-04-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True)),
                ('User_Id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
