# Generated by Django 4.0.3 on 2022-04-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
