# Generated by Django 4.0.3 on 2022-04-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='User_Id',
            new_name='user_Id',
        ),
    ]
